from typing import Protocol

from .sqlite import SQLiteClient


class Client(Protocol):
    def close(self) -> None: ...
    def create_table(self, table_name: str, columns: list[str]) -> None: ...
    def is_table_exists(self, table_name: str) -> bool: ...
    def get_column_names(self, table_name: str) -> list[str]: ...
    def drop_column(self, table_name: str, column_name: str) -> None: ...

    def rename_column(
        self, table_name: str, old_column_name: str, new_column_name: str
    ) -> None: ...
    def add_column(self, table_name: str, column_name: str) -> None: ...


def get_client() -> Client:
    return SQLiteClient()
