from typing import Any, Protocol

from .sqlite import SQLiteClient


class Client(Protocol):
    def close(self) -> None: ...
    def create_table(self, table_name: str, columns: list[str]) -> None: ...
    def is_table_exists(self, table_name: str) -> bool: ...
    def get_column_names(self, table_name: str) -> list[str]: ...
    def drop_column(self, table_name: str, column_name: str) -> None: ...

    def rename_column(
        self, table_name: str, old_column_name: str, new_column_name: str
    ) -> None: ...
    def add_column(self, table_name: str, column_name: str) -> None: ...
    def drop_table(self, table_name: str) -> None: ...

    def update_rows(
        self, table_name: str, fields: dict[str, str], where: str
    ) -> None: ...
    def delete_rows(self, table_name: str, where: str) -> None: ...

    def insert_row(
        self, table_name: str, columns: list[str], values: list[str]
    ) -> None: ...

    def insert_row_and_get_id(
        self, table_name: str, columns: list[str], values: list[str], id_column: str
    ) -> int: ...

    def is_row_exists(self, table_name: str, where: str) -> bool: ...
    def fetchone(self, sql: str, parameters: list[Any]) -> Any: ...
    def fetchall(self, sql: str, parameters: list[Any]) -> list[Any]: ...


def get_client() -> Client:
    return SQLiteClient()
